name       : Install Dependencies
description: 'Install Dependencies'

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
              ${{ runner.os }}-poetry-
      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          
          # poetry self add poetry-plugin-export      

#      - name: Create Poetry venv
#        shell: bash
#        run: |
#
#          poetry env use python3.12
#          source $(poetry env info --path)/bin/activate
#          poetry export -f requirements.txt --output requirements.txt --with dev
#      - name: Install dependencies (using PIP)
#        shell: bash
#        run: |
#          export PATH="$HOME/.local/bin:$PATH"
#          pip install -r requirements.txt
#          pip install -e .

 #this wasn't working at all
      - name: Install dependencies (using Poetry)
        shell: bash
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install
          pip install -e .
          # do this here so that we don't pollute the poetry.lock
          pip install coveralls pytest
