name       : Publish to PyPI
description: 'Publish to PyPI'

inputs:
  PYPI_API_TOKEN:
    description: 'PYPI_API_TOKEN'
    required: true


runs:
    using: 'composite'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        shell: bash
        run: | 
          poetry install

      - name: Build the package
        shell: bash
        run: | 
          poetry build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ inputs.PYPI_API_TOKEN }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ inputs.PYPI_API_TOKEN }}