name       : Poetry - Install Dependencies
description: 'Poetry - Install Dependencies'


inputs:
  pip_install:
    description: 'Extra pip installs'
    required: false
  poetry_run:
    description: 'Extra poetry run execution'
    required: false
    default: 'pip list'
  test_target:
    description: 'the target folder for the tests'
    required: false
    default: 'tests/unit'

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          #architecture: x64
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
              ${{ runner.os }}-poetry-

      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"          

      - name: Install dependencies (using Poetry)
        shell: bash
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install      

      - name: Extra pip install (using Poetry)
        if: ${{ inputs.pip_install != '' }}
        shell: bash
        run: |          
          poetry run pip install ${{inputs.pip_install}}      

      - name: Extra poetry run execution
        if: ${{ inputs.poetry_run != '' }}
        shell: bash
        run: |          
          poetry run ${{inputs.poetry_run}}
