name       : 'Publish to Docker Hub'
description: 'Publish container to docker hub'


inputs:
  DOCKERHUB_USERNAME:
    description: 'DOCKERHUB_USERNAME'
    required: true
  DOCKERHUB_TOKEN:
    description: 'DOCKERHUB_TOKEN'
    required: true
  IMAGE_NAME:
    description: 'IMAGE_NAME'
    required: true
  IMAGE_TAG:
    description: 'IMAGE_TAG'
    required: true
  DOCKER_CONTEXT:
    description: 'DOCKER_CONTEXT'
    required: true
  DOCKER_FILE:
    description: 'DOCKER_FILE'
    required: true

runs:
    using: 'composite'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ inputs.DOCKERHUB_TOKEN    }}

      - name: show details (for debugging)
        shell: bash
        run: |          
          echo "DOCKER_CONTEXT    : ${{ inputs.DOCKER_CONTEXT }}"
          echo "DOCKER_FILE       : ${{ inputs.DOCKER_FILE }}"
          echo "IMAGE_NAME        : ${{ inputs.IMAGE_NAME }}"
          echo "IMAGE_TAG         : ${{ inputs.IMAGE_TAG }}"

      - name: Build and push Docker image (${{inputs.IMAGE_NAME}}:${{inputs.IMAGE_TAG}})
        uses: docker/build-push-action@v5
        with:
          context: ${{inputs.DOCKER_CONTEXT}}
          file   : ${{inputs.DOCKER_FILE}}
          push   : true
          tags   : "${{inputs.IMAGE_NAME}}:${{inputs.IMAGE_TAG}}"
