name       : 'Publish to Docker Hub'
description: 'Publish container to docker hub'

# needs these env vars:
# DOCKER_HUB__USERNAME
# DOCKER_HUB__TOKEN
# DOCKER__CONTEXT
# DOCKER__FILE
# PACKAGE_NAME
# VERSION
runs:
    using: 'composite'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB__USERNAME }}
          password: ${{ env.DOCKER_HUB__TOKEN    }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "${{env.DOCKER__CONTEXT}}"
          file   : "${{env.DOCKER__FILE}}"
          push   : true
          tags   : "${{env.DOCKER_HUB__USERNAME}}/${{env.PACKAGE_NAME}}:${{env.VERSION}}"
