name       : 'Publish to Docker Hub'
description: 'Publish container to docker hub'


runs:
    using: 'composite'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN    }}

      - name: show details (for debugging)
        shell: bash
        run: |          
          echo "---------------------"
          echo "DOCKER_HUB__ACCOUNT : ${{ env.DOCKER_HUB__ACCOUNT }}"
          echo "DOCKER__CONTEXT     : ${{ env.DOCKER__CONTEXT }}"
          echo "DOCKER__FILE        : ${{ env.DOCKER_FILE }}"
          echo "IMAGE_NAME          : ${{ env.IMAGE_NAME }}"
          echo "VERSION             : ${{ env.VERSION }}"
          echo "---------------------"

      - name: Build and push Docker image (${{inputs.IMAGE_NAME}}:${{inputs.IMAGE_TAG}})
        uses: docker/build-push-action@v5
        with:
          context: "${{env.DOCKER__CONTEXT}}"
          file   : "${{env.DOCKER__FILE}}"
          push   : true
          tags   : "${{env.DOCKER_HUB__ACCOUNT}}/${{env.PACKAGE_NAME}}:${{env.VERSION}}"
