name       : Install Dependencies (using Poetry)
description: 'Install Dependencies  (using Poetry)'

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
              ${{ runner.os }}-poetry-

      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"          

      - name: Install dependencies (using Poetry)
        shell: bash
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install
          #pip install -e .      
          
          # for now do this here 
          #pip install coveralls pytest
