name       : CI Pipeline - DEV
on:
  push:
    branches:
      - dev

env:
  DOCKER__CONTEXT     : "."
  DOCKER__FILE        : './deploy/docker/osbot_github_actions__from_pip/Dockerfile'
  DOCKER_HUB__USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_HUB__TOKEN   : ${{ secrets.DOCKERHUB_TOKEN    }}
  GIT__BRANCH         : 'dev'
  PACKAGE_NAME        : 'osbot_github_actions'



jobs:

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Poetry - Install Dependencies
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev
        with:
          pip_install: '-r requirements-test.txt'

      - name: Run Unit Tests (using Poetry)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__run-unit-tests@dev


  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          target_branch: ${{ env.BRANCH }}
          release_type : 'minor'
    needs:
      - run-unit-tests


  publish-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: Set $Version from file
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__read_version@dev

      - name: Deploy to Docker Hub
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/docker-hub__publish@dev
    needs:
      - increment-tag
