name: 'aws__publish__s3_via_cloudfront'
description: 'aws__publish__s3_via_cloudfront'

runs:
  using: 'composite'
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id    : ${{ env.AWS_ACCESS_KEY_ID     }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ env.AWS_DEFAULT_REGION    }}

    - name: Git Update Current Branch
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

    - name: Set $Version from file
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__read_version@dev

    - name: Sync files to S3
      shell: bash
      run: |               
            aws s3 sync                                                                                                        \
                ./${{ env.PACKAGE_NAME  }} s3://${{ env.S3_PUBLISH_BUCKET  }}/${{ env.S3_PUBLISH_FOLDER  }}/${VERSION}/  \
                --delete                                                                                                       \
                --acl public-read                                                                                              \
                --cache-control "public, max-age=3600"
    
            aws s3 sync                                                                                                        \
                ./${{ env.PACKAGE_NAME  }} s3://${{ env.S3_PUBLISH_BUCKET  }}/${{ env.S3_PUBLISH_FOLDER  }}/latest/      \
                --delete                                                                                                       \
                --acl public-read                                                                                              \
                --cache-control "public, max-age=3600"

    - name: Invalidate CloudFront Cache
      shell: bash
      run: |
            aws cloudfront create-invalidation                    \
                --distribution-id ${{ env.CLOUDFRONT_DIST_ID  }}  \
                --paths "/${{ env.S3_PUBLISH_FOLDER  }}/latest/*"